export const strings = {
    request_timeout: "Timeout error. Please try again later.",
    no_internet: "Please check your connectivity and try again.",
    poor_network: "Please check your internet connection and try again.",
    non_idea_no: "ವೊಡಾಫೋನ್ ಐಡಿಯಾ ನಂಬರ್ ಅಲ್ಲ",
    server_error: "Server error. Please try again later.",
    non_vodafone_idea_no: "ವೊಡಾಫೋನ್ ಐಡಿಯಾ ನಂಬರ್ ಅಲ್ಲ",
    no_coupons_msg: "ನೀವು ಇದುವರೆಗೂ ಯಾವುದೇ ಕೂಪನ್ ಗಳಿಸಿಲ್ಲವೆಂದು ತೋರುತ್ತದೆ.",
    page_not_found_title: "ಪೇಜ್ ಕಂಡುಬಂದಿಲ್ಲ!",
    no_network_title: "ಅಯ್ಯೋ! ನೆಟ್ವರ್ಕ್ ಇಲ್ಲ",
    server_error_title: "ಅಯ್ಯೋ! ಸರ್ವರ್ ದೋಷ",
    request_timeout_title: "ಮನವಿ ಸಮಯ ಮೀರಿದೆ",
    no_notification_title: "ಇದುವರೆಗೂ ಯಾವುದೇ ನೋಟಿಫಿಕೇಶನ್‌ಗಳಿಲ್ಲ!",
    no_coupons_title: "ಯಾವುದೇ ಕೂಪನ್‌ಗಳಿಲ್ಲ",
    network_timeout_title: "ನೆಟ್ವರ್ಕ್ ಸಮಯ ಮೀರಿದೆ.",
    no_data_found_titele: "ಯಾವುದೇ ಡೇಟಾ ಕಂಡುಬಂದಿಲ್ಲ!",
    retry_btn_title: "ಮರುಪ್ರಯತ್ನಿಸಿ",
    otp_limit_expire: 'Did you try too many times? Seems like you have exceeded OTP limit',
    open_order_exist: 'Currently a complaint raised for your number is open. you can raise another complaint once it is closed. Please check the Service requests and complaints section in My account for further updates.',
    inactive_or_suspended_number1: 'This Vi number is currently',
    inactive_or_suspended_number2: ' Please pay bill to activate the number.',
    amazon_already_avail: 'Amazon Prime is a one-time benefit and you have claimed it previously.',
    amazon_reversal_deact_failure: 'Your request to cancel Amazon Prime Membership could not be processed. Please try again after sometime',
    could_not_raise_request :'Sorry, we could not raise your request due to a technical reason. Please try again or come back in a while.',
    already_raise_request_gold_game: 'You have raised a similar request with us just sometime back. Please try again after 4 hours from now.',
    unexpected_error: "Unexpected error. Please try again later.",
    no_is_suspended: "This number is currently suspended, please call 199 for more details.",
    sim_lost: "This number is suspended due to lost SIM",
    currently_request_raised:"Currently a request raised for your number is open. You can raise another request once it is closed.\nPlease check the Service requests and complaints section in My account for further updates."
}